import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./(components)/_navbar/page";
import Providersdarkmode from "./(components)/_dark-mode/_providers-darkmode/page";
import SplashProvider from "./(components)/_SplashLoader/_splashLodar-provider/page";
import  { Toaster } from "react-hot-toast";
import MySessionProvider from "@/MySessionProvider/MySessionProvider";
import  CartContextProvider  from "@/context/CartContext";
import WishlistContextProvider from "@/context/WishlistContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MO-E-Commerce",
  description: "Generated by Eng.mark onci",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      {/* suppressHydrationWarning bdif dh 3lshan by3meli error tb3 next-theam */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased selection:bg-sky-300`}
      >
        <MySessionProvider>
          <SplashProvider>
            <Providersdarkmode>
              <WishlistContextProvider>
                              <CartContextProvider>
              <Navbar />
              {children}
          <Toaster />

              </CartContextProvider>
              </WishlistContextProvider>

              
            </Providersdarkmode>
          </SplashProvider>

        </MySessionProvider>
      </body>
    </html>
  );
}
